-- stored procedure
DELIMITER $$

CREATE PROCEDURE PROCEDURE_NAME()
BEGIN
    -- SQL STATEMENTS
END $$

DELIMITER;

-- sp with parameters
-- in parameters
DELIMITER $$
CREATE PROCEDURE PROCEDURE_NAME(IN PARAMETER_NAME DATA_TYPE)
BEGIN
    -- SQL STATEMENTS
END $$
DELIMITER;

-- out parameters
DELIMITER $$
CREATE PROCEDURE PROCEDURE_NAME(OUT PARAMETER_NAME DATA_TYPE)
BEGIN 
    SELECT COUNT(*) INTO PARAMETER_NAME FROM TABLE_NAME;
END $$
DELIMITER;

-- inout parameters
DELIMITER $$
CREATE PROCEDURE PROCEDURE_NAME(INOUT PARAMETER_NAME DATA_TYPE)
BEGIN
    -- SQL STATEMENTS
END $$
DELIMITER;

-- declare variables inside procedure
DECLARE VARIABLE_NAME DATA_TYPE;

-- call stored procedure
CALL STORED_PROCEDURE_NAME(parameters);

-- conditional logic
IF CONDITION THEN
    STATEMENTS;
ELSEIF CONDITION THEN
    STATEMENTS;
ELSE
    STATEMENTS;
END IF;

-- loops
WHILE CONDITION DO
    SET STATEMENTS;
END WHILE;

-- drop stored procedure
DROP PROCEDURE PROCEDURE_NAME;

-- trigger 
-- TRIGGER_TIME : BEFORE | AFTER
-- TRIGGER_EVENT: INSERT | UPDATE | DELETE
CREATE TRIGGER TRIGGER_NAME
TRIGGER_TIME TRIGGER_EVENT
ON TABLE_NAME FOR EACH ROW 
BEGIN
...
END;

-- drop trigger
DROP TRIGGER [IF EXISTS] TRIGGER_NAME;
