--export to csv
SELECT COLUMN1,...
INTO OUTFILE FILE_PATH
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

-- import from csv
LOAD DATA INFILE FILE_PATH
INTO TABLE TABLE_NAME
FIELDS TERMINATED BY [DELIMITER]
ENCLOSED BY enclosure
LINES TERMINATED BY line_separator
IGNORE number_of_lines_to_skip;
