-- inner join : all common records from both table
SELECT COLUMN_NAMES
FROM TABLE_NAME
INNER JOIN TABLE_NAME 2
ON TABLE_NAME.COLUMN_NAME = TABLE_NAME 2.COLUMN_NAME
WHERE CONDITION;

-- left join : all records from left table
SELECT COLUMN_NAMES
FROM TABLE_NAME
LEFT JOIN TABLE_NAME 2
ON TABLE_NAME.COLUMN_NAME = TABLE_NAME 2.COLUMN_NAME
WHERE CONDITION;

-- right join : all records from right table
SELECT COLUMN_NAMES
FROM TABLE_NAME
RIGHT JOIN TABLE_NAME 2
ON TABLE_NAME.COLUMN_NAME = TABLE_NAME 2.COLUMN_NAME
WHERE CONDITION;

-- cross join
SELECT COLUMN_NAMES
FROM TABLE_NAME
CROSS JOIN TABLE_NAME 2;

-- full join
SELECT COLUMN_NAMES
FROM TABLE_NAME
FULL JOIN TABLE_NAME 2
ON TABLE_NAME.COLUMN_NAME = TABLE_NAME 2.COLUMN_NAME
WHERE CONDITION;

-- self join
SELECT COLUMN_NAMES
FROM TABLE_NAME A, TABLE_NAME 2 B
WHERE A.COLUMN_NAME = B.COLUMN_NAME;

-- delete join
DELETE TABLE_NAME
FROM TABLE_NAME  
INNER JOIN TABLE_NAME 2
ON CONDITION;

-- update join
UPDATE TABLES
SET COLUMN_NAME=VALUE1, COLUMN_NAME=VALUE2,...
FROM TABLE_NAME
JOIN TABLE_NAME 2 
ON CONDITION;

